core:
  alert:
    front:
      audio: true
      backup: 1.5
      level: 2
      object:
      - unknow
      - vehicle
      - pedestrian
      range:
      - 6
      - 4
      - 2
    rear:
      audio: true
      level: 2
      object:
      - unknow
      - vehicle
      - pedestrian
      range:
      - 3
      - 2
      - 1
    side:
      audio: true
      level: 2
      range:
      - 0.4
      - 0.4
      - 0.2
  path:
    length: 6
  record:
    path: ~/rosbag
    topics:
    - /sensing/front/livox/lidar
    - /sensing/front/livox/imu
    - /sensing/front/camera/image_raw/compressed
    - /sensing/front/camera/camera_info
    - /sensing/rear/livox/lidar
    - /sensing/rear/livox/imu
    - /sensing/rear/camera/image_raw/compressed
    - /sensing/rear/camera/camera_info
    - /sensing/io/can0/recv
machine:
  dimension:
    height: 3.0
    length: 10.8
    width: 3.0
  drive: generic
  manufacturer: catpillar
  front_sensor_id: SH-M12-015F
  front_cam_id: OPTICOM-IP-025-M12
  front_lidar_id: MID-360-026
  rear_sensor_id: SH-M12-015R
  rear_cam_id: OPTICOM-IP-026-M12
  rear_lidar_id: MID-360-027  
  mirror:
    max_x: 5.4
    max_y: 1.5
    max_z: 3.5
    min_x: -5.4
    min_y: -1.5
    min_z: -1.0
  model: ad30 
  name: cu9810
sensorkit:
  front:
    camera_rtsp_src: rtsp://root:root@10.20.30.40:554/cam0_0
    enable: true
    ext_base2lidar:
    - 4.90
    - 0.0
    - 1.95
    - 3.1415926
    - -0.159
    - 0.0
    ext_lidar2cam:
    - -0.0157274
    - 0.0903977
    - -0.0203141
    - 1.1847712
    - -0.0128777
    - 1.5680007
    ext_lidar2imu:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model: hw_v1_0
  rear:
    camera_rtsp_src: rtsp://root:root@10.20.30.41:554/cam0_0
    enable: true
    ext_base2lidar:
    - -4.0
    - 0.0
    - 0.75
    - 3.1415926
    - -0.384
    - 3.1415926
    ext_lidar2cam:
    - -0.0189742
    - 0.0014956
    - -0.012955
    - 1.2320226
    - 0.0128095
    - 1.5657301
    ext_lidar2imu:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model: hw_v1_0
system:
  image: ghcr.io/loopx-ai/clair-alert
  version: 0.1
