core:
  alert:
    front:
      audio: true
      backup: 1.5
      level: 1
      object:
      - pedestrian
      range:
      - 9
      - 6
      - 3
    rear:
      audio: true
      level: 2
      object:
      - unknown
      - vehicle
      - pedestrian
      range:
      - 3
      - 2
      - 1
    side:
      audio: true
      level: 2
      range:
      - 0.4
      - 0.2
      - 0.2
  path:
    length: 9
  record:
    path: ~/rosbag
    topics:
    - /sensing/front/livox/lidar
    - /sensing/front/livox/imu
    - /sensing/front/camera/image_raw/compressed
    - /sensing/front/camera/camera_info
    - /sensing/rear/livox/lidar
    - /sensing/rear/livox/imu
    - /sensing/rear/camera/image_raw/compressed
    - /sensing/rear/camera/camera_info
    - /sensing/io/can0/recv
    - /twist
machine:
  dimension:
    height: 1.6
    length: 11.3
    width: 2.65
  drive: generic
  manufacturer: generic
  mirror:
    max_x: 5.65
    max_y: 1.37
    max_z: 2.1
    min_x: -5.65
    min_y: -1.40
    min_z: -1.0
  model: truck
  name: generic
sensorkit:
  front:
    camera_rtsp_src: rtsp://root:root@10.20.30.40:554/cam0_0
    enable: true
    ext_base2lidar:
    - -0.19
    - -0.575
    - 2.42
    - 3.1415926
    - -0.269
    - 0.0
    ext_lidar2cam:
    - -0.0298944
    - 0.038427
    - -0.0549677
    - 1.2040941
    - -0.0040395
    - 1.5893882
    ext_lidar2imu:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model: hw_v1_0
  rear:
    camera_rtsp_src: rtsp://root:root@10.20.30.41:554/cam0_0
    enable: true
    ext_base2lidar:
    - -5.0
    - 0.0
    - 2.0
    - 3.1415926
    - 0.0
    - 3.1415926
    ext_lidar2cam:
    - -0.0189742
    - 0.0014956
    - -0.012955
    - 1.2373947
    - 0.0193625
    - 1.5871932
    ext_lidar2imu:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model: hw_v1_0
system:
  image: ghcr.io/loopx-ai/clair-alert
  version: 0.1
